[2024-07-23T15:33:10.144+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_minio_v02.sensor_minio_s3 scheduled__2024-07-22T00:00:00+00:00 [queued]>
[2024-07-23T15:33:10.184+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_minio_v02.sensor_minio_s3 scheduled__2024-07-22T00:00:00+00:00 [queued]>
[2024-07-23T15:33:10.185+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2024-07-23T15:33:10.211+0000] {taskinstance.py:1382} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2024-07-22 00:00:00+00:00
[2024-07-23T15:33:10.219+0000] {standard_task_runner.py:57} INFO - Started process 12467 to run task
[2024-07-23T15:33:10.236+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio_v02', 'sensor_minio_s3', 'scheduled__2024-07-22T00:00:00+00:00', '--job-id', '1198', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_minio_s3.py', '--cfg-path', '/tmp/tmpebis9ytr']
[2024-07-23T15:33:10.245+0000] {standard_task_runner.py:85} INFO - Job 1198: Subtask sensor_minio_s3
[2024-07-23T15:33:10.387+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_minio_v02.sensor_minio_s3 scheduled__2024-07-22T00:00:00+00:00 [running]> on host f777c2717f23
[2024-07-23T15:33:10.615+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bowen' AIRFLOW_CTX_DAG_ID='dag_with_minio_v02' AIRFLOW_CTX_TASK_ID='sensor_minio_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-22T00:00:00+00:00'
[2024-07-23T15:33:10.618+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-07-23T15:33:10.641+0000] {base.py:73} INFO - Using connection ID 'minio_s3_conn' for task execution.
[2024-07-23T15:33:10.643+0000] {connection_wrapper.py:381} INFO - AWS Connection (conn_id='minio_s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-07-23T15:33:16.925+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-07-23T15:33:21.945+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-07-23T15:33:26.960+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-07-23T15:33:31.972+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-07-23T15:33:36.989+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-07-23T15:33:42.005+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-07-23T15:33:42.017+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 144, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 31.422710559000734 seconds exceeds the specified timeout of 30.0.
[2024-07-23T15:33:42.029+0000] {taskinstance.py:1400} INFO - Immediate failure requested. Marking task as FAILED. dag_id=dag_with_minio_v02, task_id=sensor_minio_s3, execution_date=20240722T000000, start_date=20240723T153310, end_date=20240723T153342
[2024-07-23T15:33:42.055+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1198 for task sensor_minio_s3 (Sensor has timed out; run duration of 31.422710559000734 seconds exceeds the specified timeout of 30.0.; 12467)
[2024-07-23T15:33:42.097+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-23T15:33:42.128+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
