[2024-07-23T15:33:10.129+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_minio_v02.sensor_minio_s3 manual__2024-07-23T15:33:07.515671+00:00 [queued]>
[2024-07-23T15:33:10.176+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_minio_v02.sensor_minio_s3 manual__2024-07-23T15:33:07.515671+00:00 [queued]>
[2024-07-23T15:33:10.178+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2024-07-23T15:33:10.205+0000] {taskinstance.py:1382} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2024-07-23 15:33:07.515671+00:00
[2024-07-23T15:33:10.217+0000] {standard_task_runner.py:57} INFO - Started process 12466 to run task
[2024-07-23T15:33:10.228+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio_v02', 'sensor_minio_s3', 'manual__2024-07-23T15:33:07.515671+00:00', '--job-id', '1197', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_minio_s3.py', '--cfg-path', '/tmp/tmp09exohld']
[2024-07-23T15:33:10.232+0000] {standard_task_runner.py:85} INFO - Job 1197: Subtask sensor_minio_s3
[2024-07-23T15:33:10.330+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_minio_v02.sensor_minio_s3 manual__2024-07-23T15:33:07.515671+00:00 [running]> on host f777c2717f23
[2024-07-23T15:33:10.586+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bowen' AIRFLOW_CTX_DAG_ID='dag_with_minio_v02' AIRFLOW_CTX_TASK_ID='sensor_minio_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T15:33:07.515671+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-23T15:33:07.515671+00:00'
[2024-07-23T15:33:10.588+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-07-23T15:33:10.609+0000] {base.py:73} INFO - Using connection ID 'minio_s3_conn' for task execution.
[2024-07-23T15:33:10.611+0000] {connection_wrapper.py:381} INFO - AWS Connection (conn_id='minio_s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-07-23T15:33:16.955+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-07-23T15:33:21.991+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-07-23T15:33:27.039+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-07-23T15:33:32.058+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-07-23T15:33:37.072+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-07-23T15:33:42.087+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-07-23T15:33:42.106+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 144, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 31.540653228000338 seconds exceeds the specified timeout of 30.0.
[2024-07-23T15:33:42.124+0000] {taskinstance.py:1400} INFO - Immediate failure requested. Marking task as FAILED. dag_id=dag_with_minio_v02, task_id=sensor_minio_s3, execution_date=20240723T153307, start_date=20240723T153310, end_date=20240723T153342
[2024-07-23T15:33:42.177+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1197 for task sensor_minio_s3 (Sensor has timed out; run duration of 31.540653228000338 seconds exceeds the specified timeout of 30.0.; 12466)
[2024-07-23T15:33:42.263+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-23T15:33:42.285+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
