[2024-07-22T15:06:30.921+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2024-07-22T15:06:28.331934+00:00 [queued]>
[2024-07-22T15:06:30.936+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2024-07-22T15:06:28.331934+00:00 [queued]>
[2024-07-22T15:06:30.937+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2024-07-22T15:06:30.959+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-07-22 15:06:28.331934+00:00
[2024-07-22T15:06:30.969+0000] {standard_task_runner.py:57} INFO - Started process 4843 to run task
[2024-07-22T15:06:30.984+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'manual__2024-07-22T15:06:28.331934+00:00', '--job-id', '1153', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpl085x6gc']
[2024-07-22T15:06:30.989+0000] {standard_task_runner.py:85} INFO - Job 1153: Subtask create_postgres_table
[2024-07-22T15:06:31.166+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2024-07-22T15:06:28.331934+00:00 [running]> on host b8647d758ea8
[2024-07-22T15:06:31.565+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bowen' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T15:06:28.331934+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T15:06:28.331934+00:00'
[2024-07-22T15:06:31.567+0000] {sql.py:274} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            ) 
        
[2024-07-22T15:06:31.595+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-07-22T15:06:31.659+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-07-22T15:06:41.670+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Temporary failure in name resolution

[2024-07-22T15:06:41.689+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20240722T150628, start_date=20240722T150630, end_date=20240722T150641
[2024-07-22T15:06:41.735+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1153 for task create_postgres_table (could not translate host name "host.docker.local" to address: Temporary failure in name resolution
; 4843)
[2024-07-22T15:06:41.763+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-22T15:06:41.792+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
